#160521468 Improve code maintainability
davidshare/Fast-Food-Fast pull request #31
Opened 2018-09-14 17:09 UTC by davidshare

#### What does this PR do?
Improve the code maintainability

#### Description of Task to be completed?
- remove rules for checking validity of user input from the ValidateOrder class
- create a separate module to hold rules for validation
- remove strings for error message from ValidateOrder class
- create a separate module for error messages
- fix grammatical error in message for invalid orderId in the orders test file

#### How should this be manually tested?
- visit the repository on GitHub and check the readme file for the maintainability badge

#### What are the relevant pivotal tracker stories?
#160521468

2018-09-15 18:48 UTC, KaiserPhemi requested changes

2018-09-15 18:48 UTC, KaiserPhemi commented on server/middleware/orderValidator.js
> +   *
#### Nitpick
This space is unnecessary

2018-09-15 19:15 UTC, davidshare commented
Sorry I don't really understand. Should I remove the empty lines in the comment block or the entire comment.

2018-09-15 19:20 UTC, davidshare commented on server/middleware/orderValidator.js
> +   *
Sorry, I don't really understand. Should I remove the empty lines in the comment block or the entire comment?

2018-09-15 19:26 UTC, KaiserPhemi commented on server/middleware/orderValidator.js
> +   *
@davidshare 
Just the empty line

2018-09-16 01:19 UTC, KaiserPhemi approved these changes

2018-09-16 01:23 UTC, KaiserPhemi commented
Looks Good To Me (LGTM) but try & increase the Code Coverage.

2018-09-16 01:45 UTC, merged